// frontend/src/pages/Supervisionar.tsx
import { useState, useEffect, useCallback, useRef } from "react";
import { MessageCircle, ArrowRight, ArrowLeft, AlertTriangle, Loader2 } from "lucide-react";
import { GlassCard } from "@/components/ui/glass-card";
import { MainLayout } from "@/components/layout/MainLayout";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";
import { conversationsService, usersService, Conversation as APIConversation, User } from "@/services/api";
import { format } from "date-fns";

interface ConversationGroup {
  contactPhone: string;
  contactName: string;
  operatorName: string;
  lastMessage: string;
  lastMessageTime: string;
  isFromContact: boolean;
  messages: APIConversation[];
}

export default function Supervisionar() {
  const [conversations, setConversations] = useState<ConversationGroup[]>([]);
  const [operators, setOperators] = useState<User[]>([]);
  const [selectedConversation, setSelectedConversation] = useState<ConversationGroup | null>(null);
  const [selectedOperator, setSelectedOperator] = useState("all");
  const [isLoading, setIsLoading] = useState(true);

  const loadOperators = useCallback(async () => {
    try {
      const data = await usersService.list({ role: 'operator' });
      setOperators(data);
    } catch (error) {
      console.error('Error loading operators:', error);
    }
  }, []);

  // Ref para evitar loop infinito
  const selectedPhoneRef = useRef<string | null>(null);
  const isFirstLoad = useRef(true);

  // Atualizar ref quando selectedConversation mudar
  useEffect(() => {
    selectedPhoneRef.current = selectedConversation?.contactPhone || null;
  }, [selectedConversation?.contactPhone]);

  const loadConversations = useCallback(async () => {
    try {
      // Só mostrar loading na primeira vez
      if (isFirstLoad.current) {
        setIsLoading(true);
      }
      
      const data = await conversationsService.getActive();
      
      // Group conversations by contact phone
      const groupedMap = new Map<string, ConversationGroup>();
      
      data.forEach((conv) => {
        const existing = groupedMap.get(conv.contactPhone);
        if (existing) {
          existing.messages.push(conv);
          // Update last message if this one is more recent
          const convTime = new Date(conv.datetime).getTime();
          const existingTime = new Date(existing.lastMessageTime).getTime();
          if (convTime > existingTime) {
            existing.lastMessage = conv.message;
            existing.lastMessageTime = conv.datetime;
            existing.isFromContact = conv.sender === 'contact';
            existing.operatorName = conv.userName || 'Sem operador';
          }
        } else {
          groupedMap.set(conv.contactPhone, {
            contactPhone: conv.contactPhone,
            contactName: conv.contactName,
            operatorName: conv.userName || 'Sem operador',
            lastMessage: conv.message,
            lastMessageTime: conv.datetime,
            isFromContact: conv.sender === 'contact',
            messages: [conv],
          });
        }
      });

      // Sort messages within each group and groups by last message time
      const groups = Array.from(groupedMap.values()).map(group => ({
        ...group,
        messages: group.messages.sort((a, b) => 
          new Date(a.datetime).getTime() - new Date(b.datetime).getTime()
        ),
      })).sort((a, b) => 
        new Date(b.lastMessageTime).getTime() - new Date(a.lastMessageTime).getTime()
      );

      setConversations(groups);
      
      // Update selected conversation if it exists (usando ref)
      const currentSelectedPhone = selectedPhoneRef.current;
      if (currentSelectedPhone) {
        const updated = groups.find(g => g.contactPhone === currentSelectedPhone);
        if (updated) {
          setSelectedConversation(updated);
        }
      }
    } catch (error) {
      toast({
        title: "Erro ao carregar conversas",
        description: error instanceof Error ? error.message : "Erro desconhecido",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
      isFirstLoad.current = false;
    }
  }, []); // Sem dependências - usa ref

  useEffect(() => {
    loadOperators();
    loadConversations();
  }, [loadOperators, loadConversations]);

  // Poll for new messages - intervalo maior para não sobrecarregar
  useEffect(() => {
    const interval = setInterval(() => {
      loadConversations();
    }, 10000); // 10 segundos

    return () => clearInterval(interval);
  }, [loadConversations]);

  const filteredConversations = selectedOperator === "all"
    ? conversations
    : conversations.filter(c => {
        const operator = operators.find(o => o.id.toString() === selectedOperator);
        return operator && c.operatorName === operator.name;
      });

  const formatTime = (datetime: string) => {
    try {
      return format(new Date(datetime), 'HH:mm');
    } catch {
      return '';
    }
  };

  return (
    <MainLayout>
      <div className="h-[calc(100vh-6rem)] flex gap-4">
        {/* Conversations List */}
        <GlassCard className="w-80 flex flex-col" padding="none">
          {/* Header */}
          <div className="p-4 border-b border-border/50 space-y-3">
            <h2 className="font-semibold text-foreground">Supervisionar</h2>
            <Select value={selectedOperator} onValueChange={setSelectedOperator}>
              <SelectTrigger>
                <SelectValue placeholder="Todos os Operadores" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Todos os Operadores</SelectItem>
                {operators.map((op) => (
                  <SelectItem key={op.id} value={op.id.toString()}>{op.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Conversations */}
          <ScrollArea className="flex-1">
            {isLoading ? (
              <div className="flex items-center justify-center h-48">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
              </div>
            ) : filteredConversations.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-48 text-muted-foreground">
                <MessageCircle className="h-12 w-12 mb-2 opacity-50" />
                <p className="text-sm">Nenhuma conversa ativa</p>
              </div>
            ) : (
              <div className="p-2 space-y-1">
                {filteredConversations.map((conv) => (
                  <button
                    key={conv.contactPhone}
                    onClick={() => setSelectedConversation(conv)}
                    className={cn(
                      "w-full p-3 rounded-xl text-left transition-colors",
                      "hover:bg-primary/5",
                      selectedConversation?.contactPhone === conv.contactPhone && "bg-primary/10"
                    )}
                  >
                    <div className="flex items-start gap-3">
                      <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-cyan flex items-center justify-center flex-shrink-0">
                        <span className="text-sm font-medium text-primary-foreground">
                          {conv.contactName.split(' ').map(n => n[0]).join('').slice(0, 2)}
                        </span>
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <p className="font-medium text-sm text-foreground truncate">
                            {conv.contactName}
                          </p>
                          <span className="text-xs text-muted-foreground">
                            {formatTime(conv.lastMessageTime)}
                          </span>
                        </div>
                        <p className="text-xs text-warning truncate">Op: {conv.operatorName}</p>
                        <div className="flex items-center gap-1 mt-0.5">
                          {conv.isFromContact ? (
                            <ArrowLeft className="h-3 w-3 text-muted-foreground" />
                          ) : (
                            <ArrowRight className="h-3 w-3 text-primary" />
                          )}
                          <p className="text-xs text-muted-foreground truncate">
                            {conv.lastMessage}
                          </p>
                        </div>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </ScrollArea>
        </GlassCard>

        {/* Chat Area */}
        <GlassCard className="flex-1 flex flex-col" padding="none">
          {selectedConversation ? (
            <>
              {/* Chat Header */}
              <div className="p-4 border-b border-border/50 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-cyan flex items-center justify-center">
                    <span className="text-sm font-medium text-primary-foreground">
                      {selectedConversation.contactName.split(' ').map(n => n[0]).join('').slice(0, 2)}
                    </span>
                  </div>
                  <div>
                    <p className="font-medium text-foreground">{selectedConversation.contactName}</p>
                    <p className="text-xs text-muted-foreground">{selectedConversation.contactPhone}</p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-xs text-muted-foreground">Atendente</p>
                  <p className="text-sm font-medium text-warning">{selectedConversation.operatorName}</p>
                </div>
              </div>

              {/* Messages */}
              <ScrollArea className="flex-1 p-4">
                <div className="space-y-4">
                  {selectedConversation.messages.map((msg) => (
                    <div
                      key={msg.id}
                      className={cn(
                        "flex gap-2",
                        msg.sender === 'contact' ? "justify-start" : "justify-end"
                      )}
                    >
                      {msg.sender === 'contact' && (
                        <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center flex-shrink-0">
                          <span className="text-xs font-medium">
                            {selectedConversation.contactName.split(' ').map(n => n[0]).join('').slice(0, 2)}
                          </span>
                        </div>
                      )}
                      <div
                        className={cn(
                          "max-w-[70%] rounded-2xl px-4 py-2",
                          msg.sender === 'contact'
                            ? "bg-card border border-border"
                            : "bg-primary text-primary-foreground"
                        )}
                      >
                        <p className="text-sm">{msg.message}</p>
                        <p className={cn(
                          "text-xs mt-1",
                          msg.sender === 'contact' ? "text-muted-foreground" : "text-primary-foreground/70"
                        )}>
                          {formatTime(msg.datetime)}
                        </p>
                      </div>
                      {msg.sender === 'operator' && (
                        <div className="w-8 h-8 rounded-full bg-warning/20 flex items-center justify-center flex-shrink-0">
                          <span className="text-xs font-medium text-warning">OP</span>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </ScrollArea>

              {/* Read Only Banner */}
              <div className="p-3 bg-warning/10 border-t border-warning/30">
                <div className="flex items-center gap-2 justify-center text-warning">
                  <AlertTriangle className="h-4 w-4" />
                  <span className="text-sm font-medium">Modo supervisão - Somente leitura</span>
                </div>
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground">
              <MessageCircle className="h-16 w-16 mb-4 opacity-50" />
              <p className="text-lg font-medium">Selecione uma conversa</p>
              <p className="text-sm">Escolha uma conversa para supervisionar</p>
            </div>
          )}
        </GlassCard>
      </div>
    </MainLayout>
  );
}

// frontend/src/views/Supervisionar.vue
<template>
  <Layout>
    <div class="flex-1 overflow-hidden flex">
      <!-- Lista de conversas -->
      <div class="w-80 border-r border-borderColor bg-white overflow-hidden flex flex-col">
        <div class="p-4 border-b border-borderColor">
          <h3 class="font-semibold mb-4">Supervisão</h3>

          <!-- Filtro por operador -->
          <select
            v-model="selectedOperator"
            @change="filterConversations"
            class="w-full px-4 py-2 border border-borderColor rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <option value="">Todos os operadores</option>
            <option v-for="op in operators" :key="op.id" :value="op.id">
              {{ op.name }}
            </option>
          </select>
        </div>

        <div class="flex-1 overflow-y-auto scrollbar-thin">
          <div
            v-for="conv in filteredConversations"
            :key="conv.id"
            @click="selectConversation(conv)"
            :class="[
              'p-4 border-b border-borderColor cursor-pointer hover:bg-gray-50 transition-colors',
              currentConversation?.id === conv.id ? 'bg-chatActive' : ''
            ]"
          >
            <div class="flex items-start space-x-3">
              <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center flex-shrink-0">
                <span class="font-bold text-white text-sm">{{ conv.contactName?.charAt(0).toUpperCase() }}</span>
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center justify-between">
                  <h4 class="font-semibold truncate">{{ conv.contactName }}</h4>
                  <span class="text-xs text-textSecondary">{{ formatTime(conv.datetime) }}</span>
                </div>
                <p class="text-sm text-textSecondary truncate">{{ conv.message }}</p>
                <p v-if="conv.userName" class="text-xs text-primary mt-1">Operador: {{ conv.userName }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Área de conversa (somente leitura) -->
      <div v-if="currentConversation" class="flex-1 flex flex-col overflow-hidden">
        <!-- Header da conversa -->
        <div class="bg-white border-b border-borderColor p-4">
          <div class="flex items-center space-x-3">
            <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
              <span class="font-bold text-white text-sm">{{ currentConversation.contactName?.charAt(0).toUpperCase() }}</span>
            </div>
            <div>
              <h3 class="font-bold">{{ currentConversation.contactName }}</h3>
              <p class="text-xs text-textSecondary">
                {{ currentConversation.contactPhone }}
                <span v-if="currentConversation.userName" class="text-primary ml-2">
                  • Atendido por: {{ currentConversation.userName }}
                </span>
              </p>
            </div>
          </div>
        </div>

        <!-- Histórico da conversa -->
        <div class="flex-1 overflow-y-auto p-6 bg-gray-50 scrollbar-thin">
          <div class="space-y-4">
            <div
              v-for="message in messages"
              :key="message.id"
              :class="[
                'flex items-start space-x-3',
                message.sender === 'operator' ? 'justify-end' : 'justify-start'
              ]"
            >
              <div
                v-if="message.sender === 'contact'"
                class="w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center flex-shrink-0"
              >
                <span class="font-bold text-white text-xs">{{ message.contactName?.charAt(0).toUpperCase() }}</span>
              </div>

              <div
                :class="[
                  'rounded-2xl p-4 max-w-xl',
                  message.sender === 'operator'
                    ? 'bg-primary text-white rounded-tr-none'
                    : 'bg-white border border-borderColor rounded-tl-none'
                ]"
              >
                <p class="text-sm">{{ message.message }}</p>
                <span :class="['text-xs mt-2 block', message.sender === 'operator' ? 'text-gray-300' : 'text-textSecondary']">
                  {{ formatTime(message.datetime) }}
                </span>
              </div>

              <div
                v-if="message.sender === 'operator'"
                class="w-8 h-8 rounded-full bg-gradient-to-br from-warning to-error flex items-center justify-center flex-shrink-0"
              >
                <span class="font-bold text-white text-xs">{{ message.userName?.charAt(0).toUpperCase() }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Banner indicando modo leitura -->
        <div class="bg-warning bg-opacity-20 border-t border-warning p-4 text-center">
          <p class="text-sm font-medium text-warning">
            <i class="fas fa-eye mr-2"></i>
            Modo supervisão - Somente leitura
          </p>
        </div>
      </div>

      <!-- Mensagem quando não há conversa selecionada -->
      <div v-else class="flex-1 flex items-center justify-center bg-gray-50">
        <div class="text-center text-textSecondary">
          <i class="fas fa-eye text-6xl mb-4 opacity-30"></i>
          <p class="text-lg">Selecione uma conversa para visualizar</p>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '../stores/auth'
import Layout from '../components/layout/Layout.vue'
import api from '../services/api'

const authStore = useAuthStore()

const conversations = ref([])
const operators = ref([])
const selectedOperator = ref('')
const currentConversation = ref(null)
const messages = ref([])

const filteredConversations = computed(() => {
  if (!selectedOperator.value) return conversations.value
  return conversations.value.filter(c => c.userName === operators.value.find(o => o.id === selectedOperator.value)?.name)
})

onMounted(async () => {
  // Buscar operadores do segmento
  const opsResponse = await api.get('/users', {
    params: { role: 'operator', segment: authStore.user.segment }
  })
  operators.value = opsResponse.data

  // Buscar todas as conversas do segmento
  await loadConversations()
})

const loadConversations = async () => {
  const response = await api.get(`/conversations/segment/${authStore.user.segment}`)
  conversations.value = response.data
}

const filterConversations = async () => {
  await loadConversations()
}

const selectConversation = async (conv) => {
  currentConversation.value = conv
  // Buscar todas as mensagens dessa conversa
  const response = await api.get(`/conversations/contact/${conv.contactPhone}`)
  messages.value = response.data
}

const formatTime = (datetime) => {
  if (!datetime) return ''
  const date = new Date(datetime)
  return date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })
}
</script>
